version: "3.9"
services:
  proxy:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
      - ./src/config/.htpasswd:/etc/nginx/.htpasswd
      - ./src/www:/www
